Handle unexpected argument
Fix is based upon https://github.com/haskell-nix/hnix/pull/1015, and resolves the following error that occurs when running [build-clash-1.0.2](https://openbenchmarking.org/test/pts/build-clash-1.0.2):
```
error: anonymous function at ~/.phoronix-test-suite/installed-tests/pts/build-clash-1.0.2/benchmark-compilation/default.nix:24:1 called with unexpected argument 'inNixShell'

       at ~/.phoronix-test-suite/installed-tests/pts/build-clash-1.0.2/benchmark-compilation/shell.nix:2:2:

            1| {...}@args:
            2| (import ./. args).shell
             |  ^

The test run did not produce a result.


E: error: anonymous function at benchmark-compilation/default.nix:24:1 called with unexpected argument 'inNixShell'
```
This fix needs to be applied to `~/.phoronix-test-suite/installed-tests/pts/build-clash-1.0.2/benchmark-compilation/default.nix` *after* test installation, but *prior* to running the "build-clash-1.0.2" test.